### ISSUE TITLE
Deprecating /stats.json endpoints

### ISSUE THREAD

**Issue by syepes** [twosigma/satellite#22]
Hello,

This project looks very interesting but its now not compatible with the last version of Mesos (0.23) : 
https://issues.apache.org/jira/browse/MESOS-2058

**Comment by sabraham** [comment]
Thanks for the report, @syepes! We are aware of this and will be fixed in the next release.

**Comment by sabraham** [comment]
Ah sorry @syepes , there was some confusion on my part -- the stats.json endpoint in the documentation referred to Satellite's endpoint, not Mesos's -- so there was no incompatibility. Nevertheless, we are mirroring the nomenclature to hint at what is inside. I have updated the README to better clarify this.
