### ISSUE TITLE
Cannot start satellite-master, dependency problem?

### ISSUE THREAD

**Issue by jolexa** [twosigma/satellite#24]
Hello,

I've tried to build satellite and start it using the sample config:
java -jar satellite-master-0.2.0-SNAPSHOT-standalone.jar config/satellite-config.clj

The error is this:
Exception in thread "main" java.lang.RuntimeException: Unable to resolve symbol: ensure-all-tests-on-whitelisted-host-pass in this context, compiling:(/home/ubuntu/satellite/satellite-master/config/riemann-config.clj:35:18)
	at clojure.lang.Compiler.analyze(Compiler.java:6464)
....and so on...

I've dug into lein abit and there are similar results that state it may be a dependency problem, so I ran lein deps :tree and saw that there was some overrides and recommendations around the reimann verision used but I'm not sure how much to trust it due to my lack of knowledge on this subject. Any ideas or anyway I can assist troubleshooting?

**Comment by sabraham** [comment]
Hey @jolexa, thanks for the report, and sorry about that! We made some breaking API changes in 0.1.0 to 0.2.0-SNAPSHOT and did not update the sample config. (There's no longer a ensure-all-tests-on-whitelisted-host-pass function in the recipes.clj; now there's just ensure-all-tests-pass). I'll update the config to reflect the new API.

**Comment by jolexa** [comment]
Oh, great, thanks for the quick response!

**Comment by sabraham** [comment]
Should be fixed in 17a08573cb8aa3ee60d18002e8e30f3f20dfb7d7! Let me know if you have any other issues.

**Comment by jolexa** [comment]
This change allows me to start satellite-master and start getting more familar, :+1:
