### ISSUE TITLE
satellite-slave sample config, satellite-recipes not found

### ISSUE THREAD

**Issue by jolexa** [twosigma/satellite#25]
Hello,

The sample config for the slave process doesn't work well and says that satellite-recipes cannot be found. 

#riemann.codec.Event{:host "ip-10-66-84-35", :service "mesos/slave/", :state "critical", :description "command: [\"satellite-recipes\" \"free-memory\"]java.util.concurrent.ExecutionException: java.io.IOException: Cannot run program \"satellite-recipes\": error=2, No such file or directory", :metric nil, :tags nil, :time 1439514431, :ttl nil}

**Comment by sabraham** [comment]
Hey! Sorry for the delay! I'm guessing that the satellite-recipes is not in the PATH of the satellite-master process--could you double check that?

**Comment by jolexa** [comment]
Ah, sure. I never set that and I probably didn't have it configured right.
I've since abandoned my satellite tests because I couldn't figure out how
why the whitelist wasn't being written to, which is my initial use case.

**Comment by sabraham** [comment]
Ah bummer! If you try again, let us know!
