### ISSUE TITLE
More documentation or irc channel to discuss

### ISSUE THREAD

**Issue by hekaldama** [twosigma/satellite#27]
Hi there.

Thanks for satellite. Is there more documentation somewhere or an irc channel to discuss deeper details with this project?

Thanks in advance!

**Comment by sabraham** [comment]
Hey! Sure -- shoot me an email at <sunil.abraham@twosigma.com> and we can figure out a time to chat over IRC.

**Comment by sabraham** [comment]
Chatted over irc a while back and figured it out~
