### ISSUE TITLE
Detect black-hole hosts and automatically disable them

### ISSUE THREAD

**Issue by dgrnbrg** [twosigma/satellite#40]
We should be able to detect when an agent is failing some # of tasks per minute, and if that failure rate exceeds a target, we should automatically disable that agent until it can be investigated.

**Comment by mforsyth** [comment]
@dgrnbrg For this issue, when we realize that too many failures have occurred recently, can we disable the agent simply by removing it from the master's whitelist (the same way we treat  other problems which Satellite is configured to detect)?

**Comment by dgrnbrg** [comment]
You can use `on-host` and `off-host` in `satellite.recipes` to enable and disable hosts programmatically. Those functions will handle whitelist, prioritization, and UI binding.

**Comment by dgrnbrg** [comment]
You should do this entirely with the data available from the sattelite streams; you shouldn't access historical data from Riak here.

**Comment by mforsyth** [comment]
OK @dgrnbrg :+1:

**Comment by dgrnbrg** [comment]
We'll call a host a black hole if its 5 minute task failure rate is greater than 75% of it's 5 minute task launch rate, and it's 5 minute task success rate is less than 1/3 of its task failure rate. (Of course, those should be configurable settings).

To calculate this, you'll need to generate the totals of launch, success, and failures on the satellite slave. On the master, you'll need to create a 5 minute window of the ddts of those totals for each host. The sum of the values in that window will give you the 5 minute rate (w/in an error of the rate of slave transmission rate), and then you can calculate the status of the host with that information. Finally, pass the status through a flap-remover (`stable`), and have the final result control whether the host is enabled or disabled.
