### ISSUE TITLE
Blacklist?

### ISSUE THREAD

**Issue by memelet** [twosigma/satellite#41]
Is there way to use the manual whitelist to simulate forcing a node off the whitelist. For draining a node that is going down or into maintenance?

**Comment by sabraham** [comment]
Yes - if you put a manual event to `critical` for a node, it will force that node off the whitelist. You can set a ttl for the event and it will come back after that time.

**Comment by sabraham** [comment]
For more details check out the `POST` documentation at

https://github.com/twosigma/satellite/tree/master/satellite-master#post-whitelisthosthosteventevent

particularly
> `state` is either ok or critical. `ok` will turn on the host, `critical` will turn off the host

If there's something that's unclear in the documentation, let us know and we'll fix it!

**Comment by memelet** [comment]
Thanks! I missed the docs in the master and slave dirs.

**Comment by dgrnbrg** [comment]
Is there a way that we could make them more obvious from the front page?

**Comment by memelet** [comment]
Sure, maybe like Cook's subproject summary. But I would also add links to the subproject readme's.
