### ISSUE TITLE
Indicating satellite-masters to the slaves?

### ISSUE THREAD

**Issue by memelet** [twosigma/satellite#42]
It seems that the only way to indicate the masters is to explicitly list them in the slaves config. I really don't want to have to update all the slave config files if a master is lost/added/removed. Our masters will be registered with consul so I can provide the dns in the slave config. But then only one master would be resolved by the slave. 

Has any thought been given about master discover for this scenario?

**Comment by dgrnbrg** [comment]
Here's where the masters are processed: https://github.com/twosigma/satellite/blob/48a3df8d5567083f12d10cebbf7112b5a9c14fc8/satellite-slave/src/satellite_slave/core.clj#L88-L90

That's the only place in the code where we ever look at the `:satellites` key from the settings. We could instead have the https://github.com/twosigma/satellite/blob/48a3df8d5567083f12d10cebbf7112b5a9c14fc8/satellite-slave/src/satellite_slave/core.clj#L121 recompute the satellites; for example, maybe we could check if `:satellites` is a collection or a function, and if it's a function, then we could create new clients on the fly if the function's return value changed. Of course, we'd want to memoize the client creation, but I think that storing the most recent 5 clients would be sufficient.

**Comment by memelet** [comment]
Does the slave take a SIGHUP to reload its config? If so consul-template could keep the list of satellites up to date. (Or maybe simply restarting slaves does not cause much havac on the servers?)

**Comment by dgrnbrg** [comment]
The satellite slaves are meant to be fully restarted--as long as they come back w/in 60 seconds or so, there shouldn't be any problems (I can't recall the exact timeout off the top of my head).

**Comment by memelet** [comment]
Ok, for me this works great:

```
(def settings
  {:satellites [{{range service "satellite-master"}}{:host "{{.Address}}:{{.Port}}"}
                {{end}}]
  ...
```

I have the master and slave both running as docker containers, so I just have consul-template restart the slave when it updates the config.

**Comment by dgrnbrg** [comment]
Would you be interested in contributing your docker containers & consul
templates to Satellite? We'd love to have them!

**Comment by memelet** [comment]
Of course. Once everything is stable I'll clean it up and extract any local environment dependencies that may have creeped in. I also deploy with ansible. While that is not so general just yet, it could be made so.

**Comment by dgrnbrg** [comment]
We love ansible!
