### ISSUE TITLE
How to send riemann metrics to other Riemann host?

### ISSUE THREAD

**Issue by abhishekamralkar** [twosigma/satellite#59]
Guys I am trying to send satellite Riemann metrics to my Riemann server, but it's not working, every time I start satellite master it start Riemann server also 

`"riemann-tcp-server-options": {
    "host": "monitor-000-staging.abhishekamralkar.com"
  },`

I am making changes in `satellite-settings.json` file on Satellite Master servers.

**Comment by mforsyth** [comment]
Hi @abhishekamralkar, one of the main purposes of satellite-master is to act as a receptor for all of the Riemann events that are sent by the satellite-slaves - so can't be started without its own Riemann service.   "riemann-tcp-server-options" controls the network interface that Satellite's Riemann server will listen on; it doesn't change where any messages get sent.

If you want to send messages from the satellite-slaves to a separate Riemann server (not the one for Satellite-master), you can probably just add your own Riemann server to the "satellites" array in the .json configuration on each slave - so each slave will send the messages to your riemann server in addition to satellite-master.

Is this what you were trying to accomplish? 

If you want to make a change in satellite-master to forward ALL satellite events received by satellite-master (including local events related to mesos-master in addition to events sent by the satellite-slaves), you could just edit the riemann configuration for satellite-master to forward events to a separate riemann server, like this:

http://riemann.io/howto.html#forward-between-riemann-servers

**Comment by abhishekamralkar** [comment]
Thanks @mforsyth I am able to get my Mesos Cluster metrics to Riemann server.

**Comment by mforsyth** [comment]
@abhishekamralkar you're welcome.  Good luck, and let us know if you have any more issues or questions.
